from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


FACEBOOK_PAGES_PROVIDER = "facebook_pages"
INSTAGRAM_BUSINESS_PROVIDER = "instagram_business"
META_ADS_PROVIDER = "meta_ads"


@dataclass(frozen=True)
class MetricCatalogEntry:
    provider: str
    real_metric_name: str
    measurable_key: str
    display_name_en: str
    display_name_es: str
    category: str
    status: str
    required_permissions: tuple[str, ...]
    source_type: str
    has_total: bool
    has_daily_series: bool
    total_key: str | None
    daily_key: str | None
    recommended_slide: str | None
    is_primary: bool
    notes: str

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["required_permissions"] = list(self.required_permissions)
        return payload


CATALOG: dict[str, list[MetricCatalogEntry]] = {
    FACEBOOK_PAGES_PROVIDER: [
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_posts_impressions_organic",
            measurable_key="organic_impressions",
            display_name_en="Organic Impressions",
            display_name_es="Impresiones orgánicas",
            category="visibility",
            status="available",
            required_permissions=("pages_read_engagement", "read_insights"),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=True,
            total_key="organic_impressions_total",
            daily_key="daily_organic_impressions",
            recommended_slide="main_visibility_slide",
            is_primary=True,
            notes="Primary Facebook Pages visibility metric for V1 when unique reach is unavailable.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_post_engagements",
            measurable_key="engagement",
            display_name_en="Engagement",
            display_name_es="Interacciones",
            category="engagement",
            status="available",
            required_permissions=("pages_read_engagement", "read_insights"),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=True,
            total_key="engagement_total",
            daily_key="daily_engagement",
            recommended_slide="main_engagement_slide",
            is_primary=True,
            notes="Primary Facebook Pages engagement metric for V1.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_views_total",
            measurable_key="page_views",
            display_name_en="Page Views",
            display_name_es="Visitas a la página",
            category="traffic",
            status="available",
            required_permissions=("pages_read_engagement", "read_insights"),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=True,
            total_key="page_views_total",
            daily_key="daily_page_views",
            recommended_slide="page_views_slide",
            is_primary=True,
            notes="Use only for page traffic. Never alias this as impressions.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_actions_post_reactions_total",
            measurable_key="reactions",
            display_name_en="Reactions",
            display_name_es="Reacciones",
            category="engagement",
            status="available",
            required_permissions=("pages_read_engagement", "read_insights"),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=False,
            total_key="reactions_total",
            daily_key="daily_reactions",
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Use as a secondary engagement indicator in summary surfaces.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="followers_count",
            measurable_key="followers",
            display_name_en="Followers",
            display_name_es="Seguidores",
            category="audience",
            status="available",
            required_permissions=("pages_read_engagement",),
            source_type="graph_field",
            has_total=True,
            has_daily_series=False,
            total_key="followers_total",
            daily_key=None,
            recommended_slide="summary_audience_metric",
            is_primary=False,
            notes="Audience size field from the Page node.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="fan_count",
            measurable_key="fans",
            display_name_en="Fans / Page Likes",
            display_name_es="Fans / Me gusta de la página",
            category="audience",
            status="available",
            required_permissions=("pages_read_engagement",),
            source_type="graph_field",
            has_total=True,
            has_daily_series=False,
            total_key="fans_total",
            daily_key=None,
            recommended_slide="summary_audience_metric",
            is_primary=False,
            notes="Use as Page Likes. Keep separate from followers.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_impressions",
            measurable_key="page_impressions",
            display_name_en="Page Impressions",
            display_name_es="Impresiones de página",
            category="visibility",
            status="invalid_metric",
            required_permissions=("read_insights",),
            source_type="insights_metric",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide=None,
            is_primary=False,
            notes="Do not map this automatically. Meta rejects this metric in the current endpoint.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_impressions_unique",
            measurable_key="page_reach_unique",
            display_name_en="Unique Reach",
            display_name_es="Alcance único",
            category="visibility",
            status="invalid_metric",
            required_permissions=("read_insights",),
            source_type="insights_metric",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide=None,
            is_primary=False,
            notes="Do not invent reach when Meta does not return a real reach metric.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_posts_impressions",
            measurable_key="post_impressions",
            display_name_en="Post Impressions",
            display_name_es="Impresiones de publicaciones",
            category="visibility",
            status="invalid_metric",
            required_permissions=("read_insights",),
            source_type="insights_metric",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide=None,
            is_primary=False,
            notes="Unsupported in the current product-ready endpoint. Never alias to reach.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_posts_impressions_unique",
            measurable_key="post_reach_unique",
            display_name_en="Unique Post Reach",
            display_name_es="Alcance único de publicaciones",
            category="visibility",
            status="invalid_metric",
            required_permissions=("read_insights",),
            source_type="insights_metric",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide=None,
            is_primary=False,
            notes="Unsupported in the current endpoint. Never backfill from impressions or views.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="page_fans",
            measurable_key="page_fans_legacy",
            display_name_en="Page Fans (Legacy)",
            display_name_es="Fans de página (legado)",
            category="audience",
            status="invalid_metric",
            required_permissions=("read_insights",),
            source_type="insights_metric",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide=None,
            is_primary=False,
            notes="Use fan_count field instead when available.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="published_posts",
            measurable_key="published_posts",
            display_name_en="Published Posts",
            display_name_es="Publicaciones publicadas",
            category="content",
            status="pending_permission",
            required_permissions=("pages_read_user_content",),
            source_type="graph_field",
            has_total=True,
            has_daily_series=False,
            total_key="posts_analyzed_count",
            daily_key=None,
            recommended_slide="summary_content_metric",
            is_primary=False,
            notes="Requires additional Page content permissions.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="posts_analyzed",
            measurable_key="posts_analyzed",
            display_name_en="Posts Analyzed",
            display_name_es="Publicaciones analizadas",
            category="content",
            status="pending_permission",
            required_permissions=("pages_read_user_content",),
            source_type="derived",
            has_total=True,
            has_daily_series=False,
            total_key="posts_analyzed_count",
            daily_key=None,
            recommended_slide="summary_content_metric",
            is_primary=False,
            notes="Blocked until post listing is available.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="top_posts",
            measurable_key="top_post_by_engagement",
            display_name_en="Top Posts",
            display_name_es="Mejores publicaciones",
            category="content",
            status="pending_permission",
            required_permissions=("pages_read_user_content",),
            source_type="derived",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide="summary_content_metric",
            is_primary=False,
            notes="Requires access to post-level content and engagement.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="post_insights",
            measurable_key="post_insights",
            display_name_en="Post Insights",
            display_name_es="Insights de publicaciones",
            category="content",
            status="pending_permission",
            required_permissions=("pages_read_user_content",),
            source_type="insights_metric",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide=None,
            is_primary=False,
            notes="Requires post access and post insights support.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="post_comments",
            measurable_key="comments",
            display_name_en="Comments",
            display_name_es="Comentarios",
            category="content",
            status="pending_permission",
            required_permissions=("pages_read_user_content",),
            source_type="graph_field",
            has_total=True,
            has_daily_series=False,
            total_key="comments_total",
            daily_key=None,
            recommended_slide="summary_content_metric",
            is_primary=False,
            notes="Pending Page content permissions.",
        ),
        MetricCatalogEntry(
            provider=FACEBOOK_PAGES_PROVIDER,
            real_metric_name="post_shares",
            measurable_key="shares",
            display_name_en="Shares",
            display_name_es="Compartidos",
            category="content",
            status="pending_permission",
            required_permissions=("pages_read_user_content",),
            source_type="graph_field",
            has_total=True,
            has_daily_series=False,
            total_key="shares_total",
            daily_key=None,
            recommended_slide="summary_content_metric",
            is_primary=False,
            notes="Pending Page content permissions.",
        ),
    ],
    INSTAGRAM_BUSINESS_PROVIDER: [
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="reach",
            measurable_key="instagram_reach",
            display_name_en="Reach",
            display_name_es="Alcance",
            category="visibility",
            status="pending_config",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=True,
            total_key="instagram_reach_total",
            daily_key="daily_instagram_reach",
            recommended_slide="main_visibility_slide",
            is_primary=True,
            notes="Mark as available only after a real Instagram Business audit returns data.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="views_or_impressions",
            measurable_key="instagram_views_or_impressions",
            display_name_en="Views / Impressions",
            display_name_es="Vistas / Impresiones",
            category="visibility",
            status="pending_config",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=True,
            total_key="instagram_views_or_impressions_total",
            daily_key="daily_instagram_views_or_impressions",
            recommended_slide="main_visibility_slide",
            is_primary=False,
            notes="Pick the exact real Instagram metric only after live audit confirmation.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="accounts_engaged",
            measurable_key="accounts_engaged",
            display_name_en="Accounts Engaged",
            display_name_es="Cuentas interactuando",
            category="engagement",
            status="pending_config",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=True,
            total_key="accounts_engaged_total",
            daily_key="daily_accounts_engaged",
            recommended_slide="main_engagement_slide",
            is_primary=True,
            notes="Do not mark available until a real IG audit succeeds.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="total_interactions",
            measurable_key="total_interactions",
            display_name_en="Total Interactions",
            display_name_es="Interacciones totales",
            category="engagement",
            status="pending_config",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=True,
            total_key="total_interactions_total",
            daily_key="daily_total_interactions",
            recommended_slide="main_engagement_slide",
            is_primary=False,
            notes="Pending live Instagram audit.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="likes",
            measurable_key="likes",
            display_name_en="Likes",
            display_name_es="Me gusta",
            category="engagement",
            status="pending_permission",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=False,
            total_key="likes_total",
            daily_key=None,
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Pending confirmation from live API audit.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="comments",
            measurable_key="comments",
            display_name_en="Comments",
            display_name_es="Comentarios",
            category="engagement",
            status="pending_permission",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=False,
            total_key="comments_total",
            daily_key=None,
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Pending confirmation from live API audit.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="shares",
            measurable_key="shares",
            display_name_en="Shares",
            display_name_es="Compartidos",
            category="engagement",
            status="pending_permission",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=False,
            total_key="shares_total",
            daily_key=None,
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Pending confirmation from live API audit.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="saves",
            measurable_key="saves",
            display_name_en="Saves",
            display_name_es="Guardados",
            category="engagement",
            status="pending_permission",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=False,
            total_key="saves_total",
            daily_key=None,
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Pending confirmation from live API audit.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="replies",
            measurable_key="replies",
            display_name_en="Replies",
            display_name_es="Respuestas",
            category="engagement",
            status="pending_permission",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=False,
            total_key="replies_total",
            daily_key=None,
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Pending confirmation from live API audit.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="profile_views",
            measurable_key="profile_views",
            display_name_en="Profile Views",
            display_name_es="Visitas al perfil",
            category="traffic",
            status="pending_config",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=True,
            total_key="profile_views_total",
            daily_key="daily_profile_views",
            recommended_slide="summary_traffic_metric",
            is_primary=False,
            notes="Pending live Instagram audit.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="profile_actions",
            measurable_key="profile_actions",
            display_name_en="Profile Actions",
            display_name_es="Acciones del perfil",
            category="traffic",
            status="pending_permission",
            required_permissions=("instagram_business_manage_insights",),
            source_type="insights_metric",
            has_total=True,
            has_daily_series=False,
            total_key="profile_actions_total",
            daily_key=None,
            recommended_slide="summary_traffic_metric",
            is_primary=False,
            notes="Covers website clicks or similar profile actions when available.",
        ),
        MetricCatalogEntry(
            provider=INSTAGRAM_BUSINESS_PROVIDER,
            real_metric_name="followers_count",
            measurable_key="instagram_followers",
            display_name_en="Followers",
            display_name_es="Seguidores",
            category="audience",
            status="pending_config",
            required_permissions=("instagram_business_basic",),
            source_type="graph_field",
            has_total=True,
            has_daily_series=False,
            total_key="instagram_followers_total",
            daily_key=None,
            recommended_slide="summary_audience_metric",
            is_primary=False,
            notes="Pending confirmation from live Instagram Business Login audit.",
        ),
    ],
    META_ADS_PROVIDER: [
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="spend",
            measurable_key="spend",
            display_name_en="Spend",
            display_name_es="Inversión",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="spend_total",
            daily_key="daily_spend",
            recommended_slide="main_paid_media_slide",
            is_primary=True,
            notes="Core paid media cost metric.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="impressions",
            measurable_key="paid_impressions",
            display_name_en="Paid Impressions",
            display_name_es="Impresiones pagadas",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="paid_impressions_total",
            daily_key="daily_paid_impressions",
            recommended_slide="main_paid_media_slide",
            is_primary=True,
            notes="Keep namespaced under Meta Ads only.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="reach",
            measurable_key="paid_reach",
            display_name_en="Paid Reach",
            display_name_es="Alcance pagado",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="paid_reach_total",
            daily_key="daily_paid_reach",
            recommended_slide="main_paid_media_slide",
            is_primary=False,
            notes="Do not mix with organic or Facebook Pages reach.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="clicks",
            measurable_key="clicks",
            display_name_en="Clicks",
            display_name_es="Clics",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="clicks_total",
            daily_key="daily_clicks",
            recommended_slide="main_paid_media_slide",
            is_primary=False,
            notes="Core paid traffic metric.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="inline_link_clicks",
            measurable_key="link_clicks",
            display_name_en="Link Clicks",
            display_name_es="Clics en enlace",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="link_clicks_total",
            daily_key="daily_link_clicks",
            recommended_slide="main_paid_media_slide",
            is_primary=False,
            notes="Use separately from generic clicks.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="ctr",
            measurable_key="ctr",
            display_name_en="CTR",
            display_name_es="CTR",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="ctr",
            daily_key="daily_ctr",
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Derived or direct ads field depending on API response.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="cpc",
            measurable_key="cpc",
            display_name_en="CPC",
            display_name_es="CPC",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="cpc",
            daily_key="daily_cpc",
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Use only within Meta Ads namespace.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="cpm",
            measurable_key="cpm",
            display_name_en="CPM",
            display_name_es="CPM",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="cpm",
            daily_key="daily_cpm",
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Use only within Meta Ads namespace.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="actions",
            measurable_key="results",
            display_name_en="Results",
            display_name_es="Resultados",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="results_total",
            daily_key="daily_results",
            recommended_slide="main_paid_media_slide",
            is_primary=False,
            notes="Interpret according to primary action type.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="cost_per_action_type",
            measurable_key="cost_per_result",
            display_name_en="Cost per Result",
            display_name_es="Costo por resultado",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="cost_per_result",
            daily_key="daily_cost_per_result",
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Interpret according to primary action type.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="purchase_roas",
            measurable_key="roas",
            display_name_en="ROAS",
            display_name_es="ROAS",
            category="paid_media",
            status="pending_permission",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=True,
            has_daily_series=True,
            total_key="roas",
            daily_key="daily_roas",
            recommended_slide="summary_secondary_metric",
            is_primary=False,
            notes="Only mark available when the account returns purchase ROAS.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="campaign_name",
            measurable_key="campaign_name",
            display_name_en="Campaign Name",
            display_name_es="Nombre de campaña",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide="dimension",
            is_primary=False,
            notes="Technical dimension for narratives and breakdowns.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="adset_name",
            measurable_key="adset_name",
            display_name_en="Ad Set Name",
            display_name_es="Nombre de conjunto",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide="dimension",
            is_primary=False,
            notes="Technical dimension for narratives and breakdowns.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="ad_name",
            measurable_key="ad_name",
            display_name_en="Ad Name",
            display_name_es="Nombre del anuncio",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide="dimension",
            is_primary=False,
            notes="Technical dimension for narratives and breakdowns.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="campaign_id",
            measurable_key="campaign_id",
            display_name_en="Campaign ID",
            display_name_es="ID de campaña",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide="dimension",
            is_primary=False,
            notes="Technical dimension.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="adset_id",
            measurable_key="adset_id",
            display_name_en="Ad Set ID",
            display_name_es="ID de conjunto",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide="dimension",
            is_primary=False,
            notes="Technical dimension.",
        ),
        MetricCatalogEntry(
            provider=META_ADS_PROVIDER,
            real_metric_name="ad_id",
            measurable_key="ad_id",
            display_name_en="Ad ID",
            display_name_es="ID del anuncio",
            category="paid_media",
            status="pending_config",
            required_permissions=("ads_read",),
            source_type="ads_insights_field",
            has_total=False,
            has_daily_series=False,
            total_key=None,
            daily_key=None,
            recommended_slide="dimension",
            is_primary=False,
            notes="Technical dimension.",
        ),
    ],
}


def get_metric_catalog(provider: str | None = None) -> dict[str, list[dict[str, Any]]] | list[dict[str, Any]]:
    if provider is None:
        return {
            catalog_provider: [entry.to_dict() for entry in entries]
            for catalog_provider, entries in CATALOG.items()
        }
    return [entry.to_dict() for entry in CATALOG.get(provider, [])]


def get_metric_catalog_entries(provider: str | None = None) -> dict[str, list[MetricCatalogEntry]] | list[MetricCatalogEntry]:
    if provider is None:
        return {catalog_provider: list(entries) for catalog_provider, entries in CATALOG.items()}
    return list(CATALOG.get(provider, []))


def get_available_report_metrics(provider: str) -> list[dict[str, Any]]:
    return [entry.to_dict() for entry in CATALOG.get(provider, []) if entry.status == "available"]


def get_recommended_report_metrics(provider: str) -> list[dict[str, Any]]:
    return [entry.to_dict() for entry in CATALOG.get(provider, []) if entry.recommended_slide is not None]


def normalize_metric_key(provider: str, real_metric_name: str) -> str | None:
    for entry in CATALOG.get(provider, []):
        if entry.real_metric_name == real_metric_name:
            return entry.measurable_key
    return None


def is_metric_available(provider: str, real_metric_name: str) -> bool:
    for entry in CATALOG.get(provider, []):
        if entry.real_metric_name == real_metric_name:
            return entry.status == "available"
    return False


def explain_metric_availability(provider: str, real_metric_name: str) -> str:
    for entry in CATALOG.get(provider, []):
        if entry.real_metric_name != real_metric_name:
            continue
        if entry.status == "available":
            return f"{entry.display_name_en} is product-ready for {provider}."
        if entry.status == "pending_permission":
            return f"{entry.display_name_en} requires additional permissions: {', '.join(entry.required_permissions)}."
        if entry.status == "pending_config":
            return f"{entry.display_name_en} is pending configuration or live audit for {provider}."
        if entry.status == "unsupported":
            return f"{entry.display_name_en} is not supported for {provider}."
        if entry.status == "invalid_metric":
            return f"{entry.display_name_en} is invalid in the current provider endpoint and must not be aliased."
        return entry.notes
    return f"Metric {real_metric_name} is not cataloged for {provider}."
